version: "3.1"

services:
  node:
    build:
      context: .
      args:
        - NODE_ENV=development
    # you can use legacy debug config or new inspect
    #command: ../node_modules/.bin/nodemon --debug=0.0.0.0:5858
    command: ../node_modules/.bin/nodemon --inspect=0.0.0.0:9229 -L
    #network_mode: host
    ports:
      - "8001:8001"
      - "5858:5858"
      - "9229:9229"
    volumes:
      - .:/opt/app
      - ~/.upnp-remote:/home/node/.upnp-remote
      #- C:\Users\guill\.upnp-remote:/home/node/.upnp-remote
    environment:
      - NODE_ENV=development
